version: '3'
services:

  node:
    build:
      dockerfile: .build/docker/react/Dockerfile
      context: packages/react
    container_name: node
    image: node:16-alpine
    ports:
      - '3000:3000'

    volumes:
       - ./packages/react:/usr/src/app:delegated
       - ./packages/react/node_modules:/usr/src/app/node_modules:delegated

    working_dir: /usr/src/app