version: '3.9'

services:
  app:
    container_name: js-dark
    restart: always
    environment:
      - TEST_ARGUMENT=true
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - '8150:80'
    volumes:
      - /usr/src/app/node_modules
      - .:/app
